name: usrsctp
version: '0.0.0'
synopsis: An example project
description: An example project
maintainer: Philipp Balzarek


dependencies:
  - base
  - aeson
  - async
  - bytestring
  - containers
  - data-default
  - exceptions
  - lens
  - mtl
  - text
  - network >= 3.1.2.0
  - template-haskell

default-extensions:
  - ApplicativeDo
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options:
    - -Wall
    - -Werror=incomplete-patterns
    - -Werror=incomplete-uni-patterns
    - -Werror=incomplete-record-updates


library:
  dependencies:
  - base
  - bytestring
  - cereal
  source-dirs: src
  c-sources:
    - usrsctp/usrsctplib/**/*.c
    - cbits/*.c
  extra-source-files:
    - usrsctp/usrsctplib/**/*.h

  include-dirs:
    - usrsctp/usrsctplib

  cc-options:
    - -O2
    - -DSCTP_PROCESS_LEVEL_LOCKS
    - -DSCTP_SIMPLE_ALLOCATOR
    - -DSCTP_DEBUG
    - -D__Userspace__
    - -fPIC
    - -pthread
    - -Wno-address-of-packed-member


executables:
  app:
    main: Main.hs
    dependencies:
      - usrsctp
      - network
    source-dirs: app

tests:
  tests:
    dependencies:
    - usrsctp
    - hedgehog
    - tasty
    - tasty-hedgehog
    - tasty-hspec
    - hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
